set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
       	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN U2 [get_ports {ans[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ans[0]}]
set_property PACKAGE_PIN U4 [get_ports {ans[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ans[1]}]
set_property PACKAGE_PIN V4 [get_ports {ans[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ans[2]}]
set_property PACKAGE_PIN W4 [get_ports {ans[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ans[3]}]
##Buttons
set_property PACKAGE_PIN U18 [get_ports rst]						
        set_property IOSTANDARD LVCMOS33 [get_ports rst]
## leds
set_property PACKAGE_PIN U16 [get_ports {memtoreg}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {memtoreg}]
set_property PACKAGE_PIN E19 [get_ports {memwrite}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {memwrite}]
set_property PACKAGE_PIN U19 [get_ports {pcsrc}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {pcsrc}]
set_property PACKAGE_PIN V19 [get_ports {alusrc}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {alusrc}]
set_property PACKAGE_PIN W18 [get_ports {regdst}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {regdst}]
set_property PACKAGE_PIN U15 [get_ports {regwrite}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {regwrite}]
set_property PACKAGE_PIN U14 [get_ports {jump}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {jump}]
set_property PACKAGE_PIN V14 [get_ports {branch}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {branch}]
set_property PACKAGE_PIN V13 [get_ports {alucontrol[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {alucontrol[0]}]
set_property PACKAGE_PIN V3 [get_ports {alucontrol[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {alucontrol[1]}]
set_property PACKAGE_PIN W3 [get_ports {alucontrol[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {alucontrol[2]}]